### ISSUE TITLE
Should I create an api or do storage on website?

### ISSUE THREAD

**Issue by henrique945** [henrique945/web.angular.portfolio#1]
I can create an api to save all project info and images for rendering on the website or i can use info and images locally on the website.

I mean i know that using api is dinamic and doesn't need deploys to update the website, but use GET request is faster than using local files? `I want my website to be as fast as possible`.

**Comment by H4ad** [comment]
You should go with static generator sites like gatsby and nextjs, you can create your portfolio content with markdown and then turn the markdown into HTML, it's very fast and very customizable.

The best part about this setup is that you don't need an API and you can use github-pages to host your portfolio.
